const types = {
    ITEM_HAS_ERROR: 'ITEM_HAS_ERROR',
    LOGIN: 'LOGIN',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT: 'LOGOUT',
    ADD_ORDER: 'ADD_ORDER',
    FIND_ORDER: 'FIND_ORDER',
    GET_TABLE: 'GET_TABLE',
    UPDATE_TABLE: 'UPDATE_TABLE',
    TOKEN: 'TOKEN',
    GET_MENU: 'GET_MENU',
    ADD_NEW_ITEM_ORDER: 'ADD_NEW_ITEM_ORDER',
    ADD_NEW_ORDER: 'ADD_NEW_ORDER',
    GET_ORDER_ID: 'GET_ORDER_ID',
    UPDATE_ORDER: 'GET_ORDER_ID',
    DELETE_ORDER_ITEM: 'DELETE_ORDER_ITEM',
    RESET_ORDER: 'RESET_ORDER',
    GET_HISTORY: 'GET_HISTORY'
};
export default types;
